# Generated by Django 3.0.8 on 2020-08-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200823_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='education_credential',
            new_name='Add_an_education_credential',
        ),
    ]
