# Generated by Django 3.0.8 on 2020-08-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200823_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Add_current_employer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
