# Generated by Django 3.0.8 on 2020-08-24 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_add_current_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Choose_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
