# Generated by Django 3.0.8 on 2020-08-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_choose_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Choose_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
