# Generated by Django 3.0.8 on 2020-08-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200824_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Choose_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('G', 'Gay'), ('L', 'Lesbian'), ('B', 'Bi'), ('O', 'Other')], default='', max_length=1, null=True),
        ),
    ]
