# Generated by Django 3.0.8 on 2020-08-24 03:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200824_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Choose_gender',
            field=models.CharField(blank=True, choices=[(None, 'Sex:'), ('M', 'Male'), ('F', 'Female'), ('G', 'Gay'), ('L', 'Lesbian'), ('B', 'Bi'), ('O', 'Other')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
