# Generated by Django 3.0.8 on 2020-08-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200824_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Choose_banner',
            field=models.ImageField(default='default.jpg', upload_to='banner_pics'),
        ),
    ]
