# Generated by Django 3.0.8 on 2020-08-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_about_you'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='About_you',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
