# Generated by Django 3.0.8 on 2020-08-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200824_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Add_hobbies',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='Add_hometown',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='Current_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='Current_city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='Home_details',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='About_you',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
