# Generated by Django 3.0.8 on 2020-08-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200824_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Add_hobbies',
            new_name='External_links',
        ),
        migrations.AddField(
            model_name='profile',
            name='Add_Facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='Add_Instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='Add_Twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='Add_YouTube',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='Add_your_personal_website',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
