# Generated by Django 3.0.8 on 2020-08-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200826_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='About_you',
            field=models.CharField(blank=True, max_length=19999999),
        ),
        migrations.AlterField(
            model_name='profile',
            name='External_links',
            field=models.CharField(blank=True, max_length=19999),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Home_details',
            field=models.CharField(blank=True, max_length=199999),
        ),
    ]
