# Generated by Django 3.0.8 on 2020-08-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200827_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Choose_gender',
            field=models.CharField(blank=True, choices=[(None, 'Sex:'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
