# Generated by Django 3.0.8 on 2020-09-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_profile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ad',
            field=models.BooleanField(default=False),
        ),
    ]
