# Generated by Django 3.0.8 on 2020-10-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20201025_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='relationships',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
