# Generated by Django 3.0.8 on 2020-10-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20201025_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
