# Generated by Django 3.0.8 on 2020-11-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
