# Generated by Django 3.0.8 on 2020-08-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200817_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/', upload_to='post_pics'),
        ),
    ]
