# Generated by Django 3.0.8 on 2020-08-19 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200818_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='changelog',
            field=models.TextField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
    ]
