# Generated by Django 3.0.8 on 2020-08-23 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_add_an_education_credential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Add_an_education_credential',
        ),
    ]
