# Generated by Django 3.0.8 on 2020-08-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_videos_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
