# Generated by Django 3.0.8 on 2020-08-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20200826_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='Add_post_to_group',
        ),
    ]
