# Generated by Django 3.0.8 on 2020-08-28 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20200828_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='Ad_link',
            new_name='Add_a_link',
        ),
    ]
