# Generated by Django 3.0.8 on 2020-08-29 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
