# Generated by Django 3.0.8 on 2020-08-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_market_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_views',
            field=models.IntegerField(default=0),
        ),
    ]
