# Generated by Django 3.0.8 on 2020-08-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
