# Generated by Django 3.0.8 on 2020-09-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='enter_condition',
            field=models.CharField(choices=[(None, 'Condition:'), ('New', 'New'), ('Great', 'Great'), ('Good', 'Good'), ('Used', 'Used'), ('Damaged', 'Damaged')], max_length=15),
        ),
    ]
