# Generated by Django 3.0.8 on 2020-09-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_auto_20200901_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='enter_item_type',
            field=models.CharField(choices=[(None, 'Item type:'), ('Single-List Item', 'Single-List Item'), ('Restocking', 'Restocking Item')], max_length=20),
        ),
    ]
