# Generated by Django 3.0.8 on 2020-09-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='poster',
            new_name='author',
        ),
    ]
