# Generated by Django 3.0.8 on 2020-09-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_auto_20200919_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='write_comment',
        ),
    ]
