# Generated by Django 3.0.8 on 2020-09-19 15:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_auto_20200919_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='write_comment',
            field=tinymce.models.HTMLField(),
        ),
    ]
