# Generated by Django 3.0.8 on 2020-09-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_auto_20200919_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='write_comment',
            field=models.TextField(max_length=2000),
        ),
    ]
