# Generated by Django 3.0.8 on 2020-10-22 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_profile_ad'),
        ('blog', '0052_auto_20201012_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.Profile')),
                ('users', models.ManyToManyField(to='users.Profile')),
            ],
        ),
    ]
