# Generated by Django 3.0.8 on 2020-10-22 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_friend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
