# Generated by Django 3.0.8 on 2020-10-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0055_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
